# Generated by Django 4.1.3 on 2023-01-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='body',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='photo',
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default=''),
        ),
    ]
