# Generated by Django 4.1.3 on 2023-01-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='photo',
            new_name='image',
        ),
    ]
